#!/bin/csh
ps="mendocino3.ps"
r="-128/-120.5/38/43"

# Base map
gmt pscoast -R$r -JM6i -P -Yc -Slightblue -Ggrey -Na -Ba1/a1:."Mendocino Triple Junction": -K > $ps

#Cut text from original file 
awk '{$NF=""; print $0}' mendocino_2017-08-03T18.28.48.txt > focalmeca.txt

# Focal Mechanisms 
gmt psmeca focalmeca.txt -Sz0.3 -h1 -L -R -J -O -K >> $ps

# Plate boundaries 
gmt psxy -J -R platesdata.txt -W1p,black -O -K -Sf0.20/3p -t50 >> $ps

# Locate Stations 
gmt psxy OBS_coordinates.txt -R -J -i1,2 -St0.4 -W1.0,blue -Gblue -O -K >> $ps
gmt psxy wa_6_onshore_shots.txt -R -J -i2,1 -Sa0.4 -W1.0,red -Gred -O -K >> $ps
gmt psxy offtoonshore_shots.txt -R -J -i3,2 -W2p,black -Sf0.25/3p -O -K >> $ps
gmt psxy wa_6_onshore_shots.txt -R -J -i2,1 -W2p,black -Sf0.25/3p -O -K >> $ps

# Add plate labels 
gmt pstext plates_names.txt -R -J -K -O  >> $ps

gmt pslegend -R -J -O -K -DjBC+w1.5i+o-1.5/0c << EOF >> $ps
S 0.1i t 0.15i blue 0.25p,blue 0.3i OBS 
S 0.1i a 0.15i red 0.25p,red 0.3i Onshore Receivers 
EOF

gmt pslegend << END -R -J -DjBC+w1.5i+o-5.5/.1c -F+gwhite+p1p,black -K -O -P >> $ps
G 0.04i
S 0.25i c 1p - white 0.4i Normal 
G 0.11i
S 0.25i c 1p - white 0.4i Thrust
G 0.11i
S 0.25i c 1p - white 0.4i Strike-Slip
END

gmt psmeca << END -R -J -Sa.23i -O -P >> $ps
-127.6 38.76 0.0 0 90 180 5 0 0
-127.6 38.47 0.0 0 45 90 5 0 0
-127.6 38.20 0.0 0 45 -90 5 0 0
END

# Convert to PDF
gmt psconvert -Tf -Fmendocino3 $ps


# Identifying triple junction point 
#gmt psxy MTJ.txt -R -J -O -W2p,red -Si0.2i  >> $ps