#!/bin/csh
ps="anzatopo.ps"
r="-117/-116/33/34"
grd="socal_1as_hs.grd"

# Base map
gmt pscoast -R$r -JM6i -P -Y3i -S0/40/80 -Ggrey -Na,thick -Ba1/a1:."Anza": -K -Slightblue> $ps

# Cut grid to selected area
#gmt grdcut /Volumes/BEBESHITO/topography/topo30.grd -R$r -Ganza_topo.grd

# Make Color Palette Table
#gmt grd2cpt $grd -Crelief -E -Qi > anza_cpt.cpt

# Crate shade ps (gradient)
gmt grdgradient $grd -A0 -fg -Nt -Ganza_shade.grd 

# Add topography layer 
gmt grdimage $grd -R -J -Crelief -Ianza_shade.grd -K -O >> $ps

open $ps