#!/bin/csh

ps="nepal.ps"
r="84/88/26/30"

# Cut grid to selected area
gmt grdcut /Users/jdozal/Desktop/topography/topo30.grd -R$r -Gnepal_topo.grd

# Make Color Palette Table
gmt grd2cpt nepal_topo.grd -Crelief -E -Qi > nepal_cpt.cpt

# Crate shade ps (gradient)
gmt grdgradient nepal_topo.grd -A0 -fg -Nt -Gnepal_shade.grd 

# Base map
gmt pscoast -JM6i -Na -Yc -K -R$r -Ba1/a1 -P > $ps

# Add topography layer 
gmt grdimage nepal_topo.grd -R -J -K -Crelief -Inepal_shade.grd -O >> $ps

# Make Color Palette Table
# gmt grd2cpt aftershock_dipslip.grd -Cnepal -E -Qi > ad_cpt.cpt

# Crate shade ps (gradient)
gmt grdgradient aftershock_dipslip.grd -A0 -fg -Nt -Gad_shade.grd 

# Add layer
gmt grdimage aftershock_dipslip.grd -R -J -Q -Chot -Iad_shade.grd -O >> $ps


# Convert to PDF
gmt psconvert -Tf -Fnepal $ps

